# -*- coding: utf-8 -*-
"""Challenge

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10R4McAHbYHKLr8as-kC7jfzVuOjaZQgE
"""

Nama = [ "Nonong", "Leo", "Gogot", "Vanda", "Murezky"]
Nama[-1]